# Generated by Django 6.0.6 on 2026-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
