# Generated by Django 6.0.6 on 2026-06-15 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('reels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_score', models.FloatField(db_index=True, default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('spam_score', models.FloatField(db_index=True, default=0.0)),
                ('follower_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('hashtags', models.JSONField(default=list)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('creator_score', models.FloatField(db_index=True, default=0.0)),
                ('trending_score', models.FloatField(db_index=True, default=0.0)),
                ('engagement_score', models.FloatField(db_index=True, default=0.0)),
                ('freshness_score', models.FloatField(db_index=True, default=1.0)),
                ('quality_score', models.FloatField(db_index=True, default=1.0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='ReelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('hashtags', models.JSONField(default=list)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('creator_score', models.FloatField(db_index=True, default=0.0)),
                ('trending_score', models.FloatField(db_index=True, default=0.0)),
                ('engagement_score', models.FloatField(db_index=True, default=0.0)),
                ('freshness_score', models.FloatField(db_index=True, default=1.0)),
                ('quality_score', models.FloatField(db_index=True, default=1.0)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='reels.reel')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(choices=[('hashtag', 'Hashtag'), ('category', 'Category')], db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('topic_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post_impression', 'Post Impression'), ('reel_impression', 'Reel Impression'), ('reel_watch', 'Reel Watch'), ('story_view', 'Story View'), ('story_reaction', 'Story Reaction'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('save', 'Save'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('profile_visit', 'Profile Visit'), ('search', 'Search'), ('category_visit', 'Category Visit'), ('session', 'Session')], db_index=True, max_length=30)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('content_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('post', 'Post Feed'), ('reel', 'Reel Feed')], db_index=True, max_length=10)),
                ('content_ids', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed_type')},
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
