# Generated by Django 6.0.6 on 2026-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetadata',
            name='sentiment_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='reelmetadata',
            name='sentiment_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
